ecomm/ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.url')),
    path('accounts/', include('accounts.url')),
    path('product/', include('products.url')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/products/models.py
from django.contrib.auth.models import User
from distutils.command.upload import upload
from unicodedata import category
from django.db import models
from base.models import *
from django.utils.text import slugify
from django.utils.html import mark_safe

# Create your models here.


class Catogary(BaseModel):
    catogary_name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    catogary_img = models.ImageField(upload_to='catogaries')

    class Meta:
        verbose_name_plural = '1 . Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.catogary_img.url))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.catogary_name)
        super(Catogary, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.catogary_name


class SubCategory(BaseModel):
    subcategory = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, null=True, blank=True)
    catogary = models.ForeignKey(Catogary, on_delete=models.CASCADE, related_name='subcategory')
    subcategory_img = models.ImageField(upload_to='subcategory')

    class Meta:
        verbose_name_plural = '2 . Subcategories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.subcategory_img.url))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subcategory)
        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.subcategory  


class ColorVariant(BaseModel):
    color_name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = '5 . ColorVariants'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background:%s"></div>' % (self.color_name))

    def __str__(self) -> str:
        return self.color_name

class SizeVariant(BaseModel):
    size = models.CharField(max_length=100)
    price = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = '6 . SizeVariants'

    def __str__(self) -> str:
        return self.size


class Tag(BaseModel):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '7 . Tags'

    def __str__(self) -> str:
        return self.name


class Product(BaseModel):
    product_name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    catogary = models.ForeignKey(Catogary, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    price = models.IntegerField()
    discount_percent = models.FloatField(default=0)
    total_quantity = models.IntegerField(default=0)
    description = models.CharField(max_length=250, null=True, blank=True)
    product_desc = models.TextField()
    product_information = models.TextField(null=True, blank=True)
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL,null=True, blank=True)
    color_variant = models.ManyToManyField(ColorVariant, blank=True)
    size_variant = models.ManyToManyField(SizeVariant, blank=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '3 . Products'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.product_name)
        super(Product, self).save(*args, **kwargs)

    def discount(self):
        if self.discount_percent > 0:
            discounted_price = self.price - self.price * self.discount_percent / 100
            return discounted_price


    def __str__(self) -> str:
        return self.product_name

    def get_product_price_by_size(self, size):
        return self.price + SizeVariant.objects.get(size=size).price

class ProductImages(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField(upload_to='products')

    class Meta:
        verbose_name_plural = '4 . ProductImages'

    def __str__(self) -> str:
        return self.product.product_name


class ProductReview(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_text = models.TextField()
    review_rating = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.user.first_name 


class Coupon(BaseModel):
    coupon_code = models.CharField(max_length=20)
    is_expired = models.BooleanField(default=False)
    discount_price = models.IntegerField(default=100)
    min_amount = models.IntegerField(default=800)

    class Meta:
        verbose_name_plural = '8 . Coupons'

    def __str__(self) -> str:
        return self.coupon_code

ecomm/products/views.py
from django.shortcuts import render
from products.models import Product, ProductReview, SizeVariant, ColorVariant
from accounts.forms import ReviewForm

# Create your views here.


def get_product(request, slug):
    try:
        product = Product.objects.get(slug=slug)
        related_product = Product.objects.filter(catogary=product.catogary).exclude(slug=slug)[:4]
        product_review = ProductReview.objects.filter(product__slug=slug)

        context = {'product': product, 'related_product': related_product, 'product_review': product_review}

        if request.GET.get('size'):
            size = request.GET.get('size')
            price = product.get_product_price_by_size(size)
            context['selected_size'] = size
            context['updated_price'] = price
            print(price)

        return render(request, 'product/product.html', context=context)

    except Exception as e:
        print(e)

    return render(request, 'product/product.html')

ecomm/templates/product/add_catogary.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Add catogary
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="row mt-2" style="width: max-content;padding-left: 90%;">
        <a href="{% url 'dashboard' %}" class="btn btn-success float-end"><i class="bi bi-reply"></i> Back</a>
    </div>
    <div class="row">
        <div class="form-box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'base/alert.html' %}
                <div class="form-group">
                    {{form|crispy}}
                </div>
                 <p></p>
                <input type="submit" value="Add catogary" class="btn btn-success">
                <p></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomm/templates/product/add_colorvariant.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Add color
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="row mt-2" style="width: max-content;padding-left: 90%;">
        <a href="{% url 'dashboard' %}" class="btn btn-success float-end"><i class="bi bi-reply"></i> Back</a>
    </div>
    <div class="row">
        <div class="form-box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'base/alert.html' %}
                <div class="form-group">
                    {{form|crispy}}
                </div>
                 <p></p>
                <input type="submit" value="Add color" class="btn btn-success">
                <p></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomm/templates/product/add_coupon.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Add coupon
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="row mt-2" style="width: max-content;padding-left: 90%;">
        <a href="{% url 'dashboard' %}" class="btn btn-success float-end"><i class="bi bi-reply"></i> Back</a>
    </div>
    <div class="row">
        <div class="form-box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'base/alert.html' %}
                <div class="form-group">
                    {{form|crispy}}
                </div>
                 <p></p>
                <input type="submit" value="Add coupon" class="btn btn-success">
                <p></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomm/templates/product/add_sizevariant.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Add size
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="row mt-2" style="width: max-content;padding-left: 90%;">
        <a href="{% url 'dashboard' %}" class="btn btn-success float-end"><i class="bi bi-reply"></i> Back</a>
    </div>
    <div class="row">
        <div class="form-box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'base/alert.html' %}
                <div class="form-group">
                    {{form|crispy}}
                </div>
                 <p></p>
                <input type="submit" value="Add size" class="btn btn-success">
                <p></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomm/templates/product/admin_coupon.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Coupons
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 100px;">
    <div class="row mt-2" style="width: max-content;padding-left: 95%;">
        <a href="{% url 'add_coupon' %}" class="btn btn-success float-end"><i class="bi bi-plus"></i> Add</a>
    </div>
    <div class="row mt-2">
        <div class="card">
            <div class="card-body">
                <table class="table table-stripeds table-bordereds">
                    <tr>
                        <td>Coupon Name</td>
                        <td>Discount Price</td>
                        <td>Minimum Amount</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% for coupon in coupons %}
                    <tr>
                        <td>{{coupon.coupon_code}}</td>
                        <td>{{coupon.discount_price}}</td>
                        <td>{{coupon.min_amount}}</td>
                        <td><a class="btn btn-outline-primary" href=""><i class="bi bi-pen"></i></a></td>
                        <td><a href="" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ecomm/templates/product/admin_order.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Orders
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 100px;">
    <div class="row mt-2">
        <div class="card">
            <div class="card-body">
                <table class="table table-stripeds table-bordereds">
                    <tr>
                        <td>Name</td>
                        <td>Product Name</td>
                        <td>Payment Mode</td>
                        <td>Total Price</td>
                        <td>Coupon</td>
                        <td>Tracking Number</td>
                        <td>Status</td>
                        <td>Order Date</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% for order in orderitems %}
                    <tr>
                        <td>{{order.order.first_name}}</td>
                        <td>{{order.product.product_name}}</td>
                        <td>{{order.order.payment_mode}}</td>
                        <td>{{order.order.total_price}}</td>
                        <td>
                            {% if order.coupon %}
                            {{order.coupon.coupon_code}}
                            {% else %}
                            No coupon is used
                            {% endif %}
                        </td>
                        <td>{{order.order.tracking_no}}</td>
                        <td>{{order.order.status}}</td>
                        <td>{{order.created_at}}</td>
                        <td><a class="btn btn-outline-primary" href="{% url 'update_order' order.order.uid %}"><i class="bi bi-pen"></i></a></td>
                        <td><a href="" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ecomm/templates/product/admin_orderitem.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
OrderItems
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 100px;">
    <div class="row mt-2">
        <div class="card">
            <div class="card-body">
                <table class="table table-stripeds table-bordereds">
                    <tr>
                        <td>Product Name</td>
                        <td>Price</td>
                        <td>Quantity</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% for orderitem in orderitems %}
                    <tr>
                        <td>{{orderitem.product.product_name}}</td>
                        <td>{{orderitem.price}}</td>
                        <td>{{orderitem.quantity}}</td>
                        <td><a class="btn btn-outline-primary" href=""><i class="bi bi-pen"></i></a></td>
                        <td><a href="" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ecomm/templates/product/admin_product.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Products
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 100px;">
    <div class="row mt-2" style="width: max-content;padding-left: 95%;">
        <a href="{% url 'add_product' %}" class="btn btn-success float-end"><i class="bi bi-plus"></i> Add</a>
    </div>
    <div class="row mt-2">
        <div class="card">
            <div class="card-body">
                <table class="table table-stripeds table-bordereds">
                    <tr>
                        <td>Product Name</td>
                        <td>Image</td>
                        <td>Price</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% for product in products %}
                    <tr>
                        <td>{{product.product_name}}</td>
                        <td><img src="/media/{{product.product_images.first.image}}" width="50px" height="50px" alt=""></td>
                        <td>
                            {% if product.discount_percent %}
                            {{product.discount}}
                            {% else %}
                            {{product.price}}
                            {% endif %}
                        </td>
                        <td><a class="btn btn-outline-primary" href="{% url 'update_product' product.uid %}"><i class="bi bi-pen"></i></a></td>
                        <td><a href="" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ecomm/templates/product/admin_profile.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
Profile
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 100px;">
    <div class="row mt-2" style="width: max-content;padding-left: 95%;">
        <a href="{% url 'add_tag' %}" class="btn btn-success float-end"><i class="bi bi-plus"></i> Add</a>
    </div>
    <div class="row mt-2">
        {% include 'base/alert.html' %}
        <div class="card">
            <div class="card-body">
                <table class="table table-stripeds table-bordereds">
                    <tr>
                        <td>Name</td>
                        <td>email_varified</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% for profile in profile %}
                    <tr>
                        <td>{{profile.user.first_name}}</td>
                        <td>{{profile.is_email_verified}}</td>
                        <td><a class="btn btn-outline-primary" href="{% url 'edit_user' profile.uid %}"><i class="bi bi-pen"></i></a></td>
                        <td><a href="" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ecomm/templates/product/catogary.html
{% extends 'base/index.html' %}
{% block title %}
Categories
{% endblock %}

{% block body %}

<div class="container mt-5 pt-5">
    <div class="row" style="margin-top: 20px;">

        {% for catogary in catogaries %}
        <div class="col-md-3">
            <figure class="card card-product-grid">
                <div class="img-wrap embed-responsive embed-responsive-16by9" style="height: 250px ;"><img style="height: 250px ;" class="card-img-top embed-responsive-item" src="{{catogary.catogary_img.url}}"></div>
                <figcaption class="info-wrap border-top">
                    <p></p>
                    <a href="{% url 'sub_list' catogary.slug %}" class="title"><b>{{catogary.catogary_name}}</b></a>
                    <!-- <a href="{% url 'delete_catogary' catogary.uid %}" class="float-end" style="color: red;"><i class="bi bi-trash3"></i></a> -->
                    <p></p>
                </figcaption>
            </figure>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

ecomm/templates/product/edit_user.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
update User
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="form-box">
        <form method="post">
            {% csrf_token %}
            {% include 'base/alert.html' %}
            <div class="form-group">
                {{form|crispy}}
            </div>
             <p></p>
            <input type="submit" value="Update" class="btn btn-success">
            <p></p>
        </form>
    </div>
</div>

{% endblock %}

ecomm/templates/product/subcategory_dropdown_list.html
<option value="">---------</option>
{% for subcat in subcategories %}
<option value="{{ subcat.pk }}">{{ subcat.subcategory }}</option>
{% endfor %}

ecomm/templates/product/update_order.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
update order
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="form-box">
        <form method="post">
            {% csrf_token %}
            {% include 'base/alert.html' %}
            <div class="form-group">
                {{form|crispy}}
            </div>
             <p></p>
            <input type="submit" value="Update" class="btn btn-success">
            <p></p>
        </form>
    </div>
</div>

{% endblock %}

ecomm/templates/product/update_product.html
{% extends 'base/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
update product
{% endblock %}

{% block body %}
<div class="container border" style="margin-top: 120px;width: 50%;">
    <div class="form-box">
        <form method="post" id="proForm" data-subcategory-url="{% url 'ajax_load_subcategories' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'base/alert.html' %}
            <div class="form-group">
                {{form|crispy}}
            </div>
            <div class="form-group">
                {{img_form|crispy}}
            </div>
             <p></p>
            <input type="submit" value="Update" class="btn btn-success">
            <p></p>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_catogary").change(function () {
        const url = $("#proForm").attr("data-subcategory-url");  // get the url of the `load_category` view
        const catogaryId = $(this).val();  // get the selected category ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-categories/ )
            data: {
                'catogary_id': catogaryId       // add the category id to the GET parameters
            },
            success: function (data) {  // `data` is the return of the `load_subcategory` view function
                console.log(data)
                
                $("#id_subcategory").html(data);  // replace the contents of the subcategory input with the data that came from the server
                

                // let html_data = '<option value="">---------</option>';
                // data.forEach(function (subcategory) {
                //     html_data += `<option value="${subcategory.id}">${subcategory.subcategory}</option>`
                // });
                // console.log(html_data);
                // $("#id_subcategory").html(html_data);

                
            }
        });

    });
</script>

{% endblock %}